name: guidedlayout2_2045
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  assets:
    - images/pa.jpg
    - images/destination1.jpeg
    - images/destination2.jpeg
    - images/destination3.jpg

